export interface Patient {
    CountryCode: number,
    Created_Dt: string,
    ID: string,
    Patient_Address: string,
    Patient_Country: string,
    Patient_DateOfBirth: string,
    Patient_DateRecordCreated: string,
    Patient_Email: string,
    Patient_FirstName: string,
    Patient_Gender: string,
    Patient_ID: number,
    Patient_LastName: string,
    Patient_MiddleName: string,
    Patient_Mobile: string,
    Patient_NHSNumber: string,
    Patient_Postcode: number,
    Patient_Telephone: string
    Title: string,
    checksum: string,
    key: number,
    loginToken: string,
    name: string,
    owner: string,
    rev: string,
    state: string,
    token: string,
    type: string,
}

